package com.sorsix.pocetna.links

import org.springframework.stereotype.Service

@Service
class LinkDirectoryService {

    private val categories: List<LinkCategory> = listOf(
        LinkCategory(
            id = "vesti", title = "Вести", icon = "newspaper",
            links = listOf(
                SiteLink("24Вести", "https://24vesti.mk", "Онлајн медиум"),
                SiteLink("А1он", "https://a1on.mk", "Информативен портал"),
                SiteLink("Фокус", "https://fokus.mk", "Неделен весник"),
                SiteLink("Канал 5", "https://kanal5.com.mk", "Национална телевизија"),
                SiteLink("Makfax", "https://makfax.com.mk", "Информативна агенција"),
                SiteLink("Мета.мк", "https://meta.mk", "Онлајн медиум"),
                SiteLink("МИА", "https://mia.mk", "Македонска информативна агенција"),
                SiteLink("МКД", "https://mkd.mk", "Информативен портал"),
                SiteLink("МТВ", "https://mrt.com.mk", "Македонска радио телевизија"),
                SiteLink("Нова Македонија", "https://novamakedonija.com.mk", "Дневен весник"),
                SiteLink("Плусинфо", "https://plusinfo.mk", "Информативен портал"),
                SiteLink("Прес24", "https://press24.mk", "Информативен портал"),
                SiteLink("Република", "https://republika.mk", "Информативен портал"),
                SiteLink("Сакам да кажам", "https://sdk.mk", "Информативен портал"),
                SiteLink("Сител", "https://sitel.com.mk", "Национална телевизија"),
                SiteLink("Слободен печат", "https://slobodenpecat.mk", "Дневен весник"),
                SiteLink("Телма", "https://telma.com.mk", "Национална телевизија"),
                SiteLink("Утрински весник", "https://utrinskivesnik.mk", "Дневен весник"),
            ),
        ),
        LinkCategory(
            id = "sport", title = "Спорт", icon = "trophy",
            links = listOf(
                SiteLink("ФФМ", "https://ffm.mk", "Фудбалска федерација на Македонија"),
                SiteLink("Гол.мк", "https://gol.mk", "Спортски портал"),
                SiteLink("КФСМ", "https://kfsm.mk", "Кошаркарска федерација на Северна Македонија"),
                SiteLink("МОК", "https://mok.org.mk", "Македонски олимписки комитет"),
                SiteLink("Сакамфудбал", "https://sakamfudbal.mk", "Фудбалски портал"),
                SiteLink("Сител Спорт", "https://sitel.com.mk/sport", "Спортски вести"),
                SiteLink("Спортска Мрежа", "https://sportskamreza.mk", "Спортски портал"),
                SiteLink("SportSport.mk", "https://sportsport.mk", "Спортски вести"),
            ),
        ),
        LinkCategory(
            id = "vlada", title = "Власт и институции", icon = "building-columns",
            links = listOf(
                SiteLink("Агенција за вработување", "https://av.gov.mk", "АВРСМ"),
                SiteLink("Централен регистар", "https://crm.com.mk", "Централен регистар на РСМ"),
                SiteLink("Државен завод за статистика", "https://stat.gov.mk", "Статистички податоци"),
                SiteLink("е-Управа", "https://uslugi.gov.mk", "Државни е-услуги"),
                SiteLink("МВР", "https://mvr.gov.mk", "Министерство за внатрешни работи"),
                SiteLink("Народен правобранител", "https://ombudsman.mk", "Омбудсман на РСМ"),
                SiteLink("Претседател", "https://pretsedatel.mk", "Кабинет на претседателот"),
                SiteLink("Собрание", "https://sobranie.mk", "Собрание на РСМ"),
                SiteLink("УЈП", "https://ujp.gov.mk", "Управа за јавни приходи"),
                SiteLink("Уставен суд", "https://ustavensud.mk", "Уставен суд на РСМ"),
                SiteLink("Влада на РСМ", "https://vlada.mk", "Влада на Република Северна Македонија"),
            ),
        ),
        LinkCategory(
            id = "banki", title = "Банки и финансии", icon = "landmark",
            links = listOf(
                SiteLink("Халк Банка", "https://halkbank.mk", "Халк Банка АД Скопје"),
                SiteLink("Комерцијална банка", "https://kb.mk", "Комерцијална банка АД Скопје"),
                SiteLink("Македонска берза", "https://mse.mk", "Македонска берза на хартии од вредност"),
                SiteLink("НБРМ", "https://nbrm.mk", "Народна банка на РСМ"),
                SiteLink("НЛБ Банка", "https://nlb.mk", "НЛБ Банка АД Скопје"),
                SiteLink("ПроКредит Банка", "https://procreditbank.com.mk", "ПроКредит Банка АД Скопје"),
                SiteLink("Шпаркасе Банка", "https://sparkasse.mk", "Шпаркасе Банка Македонија"),
                SiteLink("Стопанска банка", "https://stb.com.mk", "Стопанска банка АД Скопје"),
                SiteLink("УНИБанка", "https://unibank.com.mk", "УНИБанка АД Скопје"),
            ),
        ),
        LinkCategory(
            id = "obrazovanie", title = "Образование", icon = "graduation-cap",
            links = listOf(
                SiteLink("Американ колеџ Скопје", "https://aac.edu.mk", "American College Skopje"),
                SiteLink("Биро за развој на образованието", "https://bro.gov.mk", "БРО"),
                SiteLink("Еду.мк", "https://edu.mk", "Образовен портал"),
                SiteLink("Министерство за образование", "https://mon.gov.mk", "МОН"),
                SiteLink("МСУ", "https://msu.edu.mk", "Меѓународен славјански универзитет"),
                SiteLink("УГД", "https://ugd.edu.mk", "Универзитет Гоце Делчев - Штип"),
                SiteLink("УКИМ", "https://ukim.edu.mk", "Универзитет Св. Кирил и Методиј - Скопје"),
                SiteLink("УКЛО", "https://uklo.edu.mk", "Универзитет Св. Климент Охридски - Битола"),
            ),
        ),
        LinkCategory(
            id = "biznis", title = "Бизнис и економија", icon = "briefcase",
            links = listOf(
                SiteLink("Бизнис Инфо", "https://biznisinfo.mk", "Бизнис портал"),
                SiteLink("БизнисМрежа", "https://biznismreza.mk", "База на бизнис информации"),
                SiteLink("Економија и бизнис", "https://ebizmagazine.com", "Магазин"),
                SiteLink("Фактор", "https://faktor.mk", "Портал за економија и бизнис"),
                SiteLink("Капитал", "https://kapital.mk", "Бизнис портал"),
                SiteLink("Лидер", "https://lider.mk", "Бизнис портал"),
                SiteLink("Стопанска комора", "https://mchamber.mk", "Стопанска комора на Македонија"),
            ),
        ),
        LinkCategory(
            id = "tehnologija", title = "Технологија", icon = "microchip",
            links = listOf(
                SiteLink("Емитер", "https://emiter.com.mk", "Списание за наука и техника"),
                SiteLink("Иновативност", "https://inovativnost.mk", "Портал за иновации и претприемништво"),
                SiteLink("ИТ.мк", "https://it.mk", "IT портал"),
                SiteLink("Конект.мк", "https://konekt.mk", "Технологија и иновативни науки"),
                SiteLink("Smartportal.mk", "https://smartportal.mk", "Портал за паметна технологија"),
                SiteLink("USB.mk", "https://usb.mk", "Технологија, наука и интернет"),
            ),
        ),
        LinkCategory(
            id = "zabava", title = "Забава и ТВ", icon = "tv",
            links = listOf(
                SiteLink("Fakulteti.mk", "https://fakulteti.mk", "Магазин за млади"),
                SiteLink("Sakam.mk", "https://sakam.mk", "Лајфстајл портал"),
                SiteLink("Star.mk", "https://star.mk", "Забавен портал"),
                SiteLink("ТВ Програма", "https://tvprogram.mk", "Телевизиски програми"),
            ),
        ),
        LinkCategory(
            id = "mapi", title = "Карти, превоз и услуги", icon = "map-location-dot",
            links = listOf(
                SiteLink("АМСМ", "https://amsm.mk", "Автомото сојуз на Македонија"),
                SiteLink("Google Maps", "https://maps.google.com", "Карти и навигација"),
                SiteLink("ЈСП Скопје", "https://jsp.com.mk", "Јавен градски превоз - Скопје"),
                SiteLink("Македонски железници", "https://mztransport.mk", "Железнички превоз"),
                SiteLink("Скопски аеродроми", "https://airports.com.mk", "Аеродроми во РСМ"),
            ),
        ),
        LinkCategory(
            id = "turizam", title = "Туристички агенции", icon = "plane",
            links = listOf(
                SiteLink("Arbotravel", "https://arbotravel.com/", "Туристичка агенција"),
                SiteLink("Atlantis", "https://www.atlantis.mk/", "Туристичка агенција"),
                SiteLink("Atlas Plus", "https://atlasplus.mk/", "Туристичка агенција"),
                SiteLink("Aurora", "https://aurora.mk/", "Туристичка агенција"),
                SiteLink("Balkan Fun", "https://balkanfun.mk/", "Туристичка агенција"),
                SiteLink("Camellia Travel", "https://www.camelliatravel.com.mk/", "Туристичка агенција"),
                SiteLink("Diplomatic Travel", "https://www.diplomatic.com.mk/", "Туристичка агенција"),
                SiteLink("ETC Travel", "https://etc.mk/", "Туристичка агенција"),
                SiteLink("Fibula Air Travel", "https://www.fibula.com.mk/", "Туристичка агенција"),
                SiteLink("Fly Turizam", "https://www.flyturizam.com/", "Туристичка агенција"),
                SiteLink("Iguana", "https://iguana.com.mk/", "Туристичка агенција"),
                SiteLink("Inex", "https://inex.com.mk/", "Туристичка агенција"),
                SiteLink("InTravel", "https://intravel.mk/", "Туристичка агенција"),
                SiteLink("JK Travel", "https://jk.mk/", "Туристичка агенција"),
                SiteLink("Jungle Tribe", "https://www.jungletribe.mk/", "Туристичка агенција"),
                SiteLink("Kondor Travel", "https://kondortravel.com/", "Туристичка агенција"),
                SiteLink("Магелан Травел", "https://magelantravel.mk/", "Туристичка агенција"),
                SiteLink("Net-Bay Travel", "https://www.net-bay.com.mk/", "Туристичка агенција"),
                SiteLink("Papillon", "https://papillon.com.mk/", "Туристичка агенција"),
                SiteLink("Pilot Travel", "https://www.pilottravel.com.mk/", "Туристичка агенција"),
                SiteLink("Puzzle Travel", "https://puzzlegroup.mk/", "Туристичка агенција"),
                SiteLink("Savana Travel", "https://www.savana.travel/", "Туристичка агенција"),
                SiteLink("Скаут", "https://skaut.mk/", "Туристичка агенција"),
                SiteLink("Terra Travel", "https://terratravel.com.mk/", "Туристичка агенција"),
                SiteLink("Voyager", "https://voyager.com.mk/", "Туристичка агенција"),
                SiteLink("Waikiki", "https://www.waikiki.mk/", "Туристичка агенција"),
            ),
        ),
        LinkCategory(
            id = "pošta", title = "Пошта, комунални и е-услуги", icon = "envelope",
            links = listOf(
                SiteLink("А1 Македонија", "https://a1.mk", "Телекомуникации"),
                SiteLink("АД ЕСМ", "https://esm.com.mk", "Електрани на Северна Македонија"),
                SiteLink("ЕВН", "https://evn.mk", "Дистрибуција на електрична енергија"),
                SiteLink("Македонски телеком", "https://telekom.mk", "Телекомуникации"),
                SiteLink("Пошта на Северна Македонија", "https://posta.com.mk", "Јавно претпријатие"),
            ),
        ),
        LinkCategory(
            id = "shopping", title = "Шопинг", icon = "cart-shopping",
            links = listOf(
                SiteLink("Ananas", "https://ananas.mk/", "Онлајн продавница"),
                SiteLink("Anhoch", "https://www.anhoch.com/", "Компјутери и техника"),
                SiteLink("DDStore", "https://ddstore.mk/", "Компјутери и ИТ опрема"),
                SiteLink("eKupi", "https://www.ekupi.mk/", "Онлајн продавница"),
                SiteLink("Нептун", "https://www.neptun.mk/", "Техника и бела техника"),
                SiteLink("Pazar3", "https://www.pazar3.mk/", "Огласи"),
                SiteLink("Reklama5", "https://reklama5.mk/", "Огласи"),
                SiteLink("Setec", "https://setec.mk/", "Техника и компјутери"),
                SiteLink("Стокомак", "https://www.stokomak.com.mk/", "Супермаркет со онлајн продажба"),
                SiteLink("Техномаркет", "https://tehnomarket.com.mk/", "Техника и бела техника"),
            ),
        ),
        LinkCategory(
            id = "socijalni", title = "Социјални медиуми", icon = "users",
            links = listOf(
                SiteLink("Facebook", "https://www.facebook.com/", "Социјална мрежа"),
                SiteLink("Instagram", "https://www.instagram.com/", "Социјална мрежа"),
                SiteLink("LinkedIn", "https://www.linkedin.com/", "Професионална мрежа"),
                SiteLink("Telegram", "https://telegram.org/", "Апликација за пораки"),
                SiteLink("TikTok", "https://www.tiktok.com/", "Видео социјална мрежа"),
                SiteLink("Viber", "https://www.viber.com/", "Апликација за пораки"),
                SiteLink("X", "https://x.com/", "Социјална мрежа"),
                SiteLink("YouTube", "https://www.youtube.com/", "Видео платформа"),
            ),
        ),
    )

    fun getCategories(): List<LinkCategory> = categories
}
